excluded:
  - Pods
  - "**/*Tests.swift"
  - Libraries
  - "**/Project.swift"
  - "Modules/**Derived/*"
  # swinftlint 경고가 중복으로 뜨네?..
  - "**/Interfaces/**"

included:

disabled_rules:
  - leading_whitespace
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - identifier_name
  - type_name
  - file_length
  - line_length
  - function_body_length
  - cyclomatic_complexity
  - function_parameter_count

nesting:
  type_level:
    warning: 5
    error: 6
type_body_length:
  warning: 400
  error: 450
